# .github/workflows/deploy.yml

name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0' # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone --depth 1 --branch main https://github.com/rohanmhetar/rohanmhetar.github.io.git out-deploy
          rm -rf out-deploy/*
          cp -r out/* out-deploy/
          cd out-deploy
          git add .
          git commit -m "Deploy static site [skip ci]"
          git push origin main --force
